name: Checkstyle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:
    runs-on: windows-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Télécharger Checkstyle
        run: |
          mkdir -p tools
          curl -L -o tools/checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar

      - name: Exécuter Checkstyle
        run: |
          java -jar tools/checkstyle.jar -c checkstyle.xml src/
