name: Checkstyle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run Checkstyle
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Download Checkstyle
        run: |
          if (-Not (Test-Path "tools")) { New-Item -ItemType Directory -Path "tools" }
          Invoke-WebRequest -Uri https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar -OutFile tools/checkstyle.jar
        shell: pwsh


      - name: Run Checkstyle
        run: |
          java -jar tools/checkstyle.jar -c checkstyle.xml src/
